# Aufgabe 1

Im ersten Schritt muss Numpy importiert werden um später auf Funktionen zurückgreifen zu können

In [6]:
# Programmgeruest zu Versuch 1, Aufgabe 1
import numpy as np

Als nächstes Initialisierung der Datenmatrix, sowie des Testdatenvektors

In [7]:
# ***** MAIN PROGRAM ********

# (i) Generate dummy data 
X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]]);      # data matrix X: list of data vectors (=database) of dimension D=3
x = np.array([1.5,3.6,5.7]);                          # a test data vector
print ("Data matrix X=\n",X)
print ("Test vector x=",x)

Data matrix X=
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Test vector x= [1.5 3.6 5.7]


Hier wird für jeden Eintrag in der Datenmatrix die euklidische Distanz zum Testvektor berechnet

In [5]:
# (ii) Print all Euklidean distances to test vector x
print ("Euklidean distances to x: ", [np.linalg.norm(i-x) for i in X])   #compute list of Euklidean distances   

Euklidean distances to x:  [3.178049716414141, 1.8708286933869709, 1.7029386365926402, 2.8809720581775866]


# Aufgabe 1a

__Schreiben Sie eine Python-Funktion getKNearestNeighbor(X, x, k=1) welche zum Testvektor x eine Index-Liste der k-Nearest-Neighbors in der Datenmatrix X zurückgibt.__

In [33]:
def getKNearestNeighbors(x,X,k=1):  # realizes nearest neighbor search of x in database
    """
    compute the k nearest neighbors for a query vector x given a data matrix X
    :param x: the query vector x
    :param X: the N x D data matrix (in each row there is data vector) as a numpy array
    :param k: number of nearest-neighbors to be returned
    :return: return list of k line indixes referring to the k nearest neighbors of x in X
    """
    if k-1 > X.size or k < 0: # check for invalid inputs for k
        return -1
    return [np.argsort([np.linalg.norm(i-x) for i in X])[j] for j in range(k)] # return indexes of k smallest distances

# Aufgabe 1b

zum Schluss wird die Funktion aufgerufen und das Ergebnis aufgearbeitet ausgegeben

In [34]:
# (iii) Search for k nearest neighbor
k=2
idx_knn = getKNearestNeighbors(x,X,k)                  # get indexes of k nearest neighbors
print ("idx_knn=",idx_knn)

# (iv) output results
print ("The k Nearest Neighbors of x are the following vectors:")
for i in range(k):
    idx=idx_knn[i]
    print ("The", i+1, "th nearest neighbor is: X[",idx,"]=",X[idx]," with distance ", np.linalg.norm(X[idx]-x))

idx_knn= [2, 1]
The k Nearest Neighbors of x are the following vectors:
The 1 th nearest neighbor is: X[ 2 ]= [3 4 5]  with distance  1.7029386365926402
The 2 th nearest neighbor is: X[ 1 ]= [2 3 4]  with distance  1.8708286933869709


# Aufgabe 1c

Wie viele Rechenschritte in Abhängigkeit von N:=len(X), D:=len(x)und k braucht Ihr Programm, um eine Anfrage zu bearbeiten (Angabe in O-Notation reicht)? Kennen Sie schnellere Verfahren?

Rechenschritte :     

Jede Berechnung der Distanz benötigt O(D) Rechenschritte.
Die Berecnhung der Distanz muss also N mal durchgeführt werden und die Funktion benötigt daher O(N*D) Rechenschritte.
Das sortieren der Distanzen benötigt O(n log(n) Rechenschritte
Die Distanzen müssen zum Schluss noch k mal auf das Array (zugeriffen werden) O(k)
Zusammen ergibt sich für die Funktion folgende zusammengesetzte Abhängigkeit: O(N*D + N log(N) + k) 

schnelleres Verfahren vor allem für große Datenmengen oder Dimensionen sind Kd-trees unter der Annahme eines balancierten Baumes